import { cn } from "#/utils/dom-utils";
import type { Metadata } from "next";
import "./globals.css";
import { GlobalProviders } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body className={cn("min-h-screen bg-background")}>
        <GlobalProviders>{children}</GlobalProviders>
      </body>
    </html>
  );
}
